### ISSUE TITLE
Feature: Allow legacy versions of each compiler

### ISSUE THREAD

**Issue by ThomasLobker** [NeoResearch/neocompiler-eco#24]
If we could recompile open-source contracts with legacy versions of the compiler, then we would be able to verify if it matches with the script hash on the blockchain. This would greatly improve trust and security for NEP-5 tokens (and other open-source smart contracts). Blockchain explorers would be able to display the actual source code (given that the source code is available) for each deployed smart contract.

**Comment by igormcoelho** [comment]
Hi Thomas, I liked a lot your idea. This can mean some extra overhead for our servers, but, who cares anyway :D it's for a good cause hahahah
We should first achieve some versioning convention for all compiling tools, because as you may have noticed, tools in Neo ecosystem don't usually have tags or unique names...
So, my first approach for naming could be X_Y_Z_A_B:
- language name (csharp)
- main maintainer name (neo)
- compiler release date (29052018) ddmmyyyy
- compiler tag, commit or partial commit (b18eb645)
- system os (ubuntu1710)
- dependencies (mono14......) This part should be quite free, the more explanation the better :)
So, we could theoretically provide a docker image like: neo-compiler:csharp_neo_29052018_b18eb645_ubuntu1710_mono14
And PROBABLY we could reproduce that in a near future :)

In fact, I believe compiler should come with a compiler.json specification, and  smart contracts should return an informative string (we can propose a NEP for it!), so everybody will know how this contract was compiled.

protocol.json could be:
{
    "language" : "csharp",
    "maintainer" : "neo",
    "release_date" : "29-05-2018",
    "tag" : "b18eb645",
    "system" : "ubuntu1710",
    "dependencies": [
      {
         "mono" : "14"
      }
    ]
}

Perhaps I'm overcomplicating things, but in opinion, if you want anything to be reproducible in this crazy environment, this could be a direction. Opinions???

**Comment by ThomasLobker** [comment]
@igormcoelho thank you so much for this insight. The JSON definition that holds all environmental parameters would be absolutely briliant. We would still need some relevant data on the smart contract level as well, something that points to where to find the source code (and where to find the compiler.json as well).

It can be part of the dApp NEP proposal in my opinion:
https://github.com/neo-project/proposals/pull/46

**Comment by igormcoelho** [comment]
@ThomasLobker  sorry for the delay, the idea is still on the table.. just time is short :)
I just thought this project will fit fine in another project we have, called `neo-tests`. The idea I have now is:
- you chose the language and pass the exact commit number or tag;
- the compiler is build on-the-fly with the desired configuration (may take a few minutes);
- the compiling process is made;
- everything is dropped.

The difference from our neocompiler.io project is that we must provide only a few pre-built options, in order to the viable to maintain them all on disk (because the purpose is to compile quickly). But if you just want to test a legacy version, it's ok to wait a few minutes. Do you agree?

**Comment by ThomasLobker** [comment]
@igormcoelho completely agreed. I think once you've built a compiler we can keep it on disk for future usage, so only the first time that it's selected it will take a couple of minutes. Disk space is cheap, so that should be no problem, but I can always help out with that.

Once we have this, we can use it audit projects and verify the script hash, even if the projects don't want to open source their contract.

**Comment by igormcoelho** [comment]
That's true @ThomasLobker ... if specific images are created and properly named, they could be invoked and kept on disk (as docker creates incremental images, only the build output will remain). We are currently working in a full separation of consensus nodes in our network, which will be the basis of neo-tests project. After that, releasing this new testing part will be quick and easy.

**Comment by vncoelho** [comment]
Closed through https://github.com/NeoResearch/neocompiler-eco/commit/77db3517d51dcab6ed5b911b15d4e8784be52569.

Still need more features.
