### ISSUE TITLE
Incorrect integer to byte array conversion for big numbers

### ISSUE THREAD

**Issue by mialbu** [NeoResearch/neocompiler-eco#93]
**Problem**
When using the conversion `BigInteger <-> Little-Endian ByteArray` in the [Neo Compiler](https://neocompiler.io/#nav-conversors/), the conversion is no longer correct if the number gets too big (probably when exceeding 64 bits).

**Examples**
`123456789012345678901234` -> `0000006da0101f9b241a00`
`123456789012345678901234567890` -> `0000000000e073c3f60fe98e0100`

**Comment by igormcoelho** [comment]
Thanks for reporting @mialbu , we'll see into it ASAP.
From what I remember, we had a manual implementation of biginteger in js that performed operations perfectly, I'll double-check if we have adopted some thirdparty lib in the meanwhile. When dealing with Number in js, there's a limitation around 60 bits, as far as I remember (as it starts to lose precision), but that don't happen in string representations of integers. I'll double check this conversion as well.

**Comment by igormcoelho** [comment]
As a follow up, the good news is that I can confirm that the issue is indeed an invalid casting to Number (that's why it fails after around 60 bits).
According to [csBigInteger-cpp](https://github.com/neoresearch/csbiginteger-cpp) demo, the following output would be expected:

```
cd demo/ && make

./demo_cshand 
demonstration for csBigInteger (Engine: 'HandBigInt')
usage: <operation> <enter> <number> <enter> <number <enter>
avaliable operations are: + - / * % ^ > < 0x 0b (0x and 0b are conversions to hex big endian and binary)

please type the operation: 0x
expects 1 number(s)
please type first number (in decimal, or unsigned hex with prefix 0x, or binary prefix 0b):123456789012345678901234
number is (decimal) '123456789012345678901234'
conversion: 0x1a249b1f10a06c96aff2

please type the operation: 0x
expects 1 number(s)
please type first number (in decimal, or unsigned hex with prefix 0x, or binary prefix 0b):123456789012345678901234567890
number is (decimal) '123456789012345678901234567890'
conversion: 0x018ee90ff6c373e0ee4e3f0ad2
```

Good news is that we already have our classic js implementation (also in [csBigInteger](https://github.com/neoresearch/csbiginteger) macro project), but I'll see with @vncoelho if we can quickly port our C++ implementation into a js package... The reason is that this C++ project is heavily tested, so it's very unlikely to deviate from standard (we test against official Mono library since 2019). I guess this port will also be of much larger future interest as well for Neo community. Let's see.

So, the fix is on the way :)
